language: generic
dist: xenial
sudo: required

install:
- sudo apt-get update
- sudo apt-get -y upgrade
- curl -O https://storage.googleapis.com/golang/go1.11.2.linux-amd64.tar.gz
- tar -xvf go1.11.2.linux-amd64.tar.gz
- sudo apt-get install golang-go
  
script:
- bash test.sh
