language: generic
dist: xenial
sudo: required

install:
- sudo apt-get update
- wget https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
- sudo tar -xvf go1.10.1.linux-amd64.tar.gz
- sudo apt-get install golang-go
  
script:
- bash test.sh
